server:
  port: 8123

jcasbin:
  url: jdbc:mysql://localhost:3306/casbin?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456
  model-path: conf/model.conf